apiVersion: skaffold/v2alpha3
kind: config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticketing-dev-417014
  artifacts:
    - image: us.gcr.io/ticketing-dev-417014/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: us.gcr.io/ticketing-dev-417014/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: '**/*.js'
            dest: .
    - image: us.gcr.io/ticketing-dev-417014/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: us.gcr.io/ticketing-dev-417014/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: us.gcr.io/ticketing-dev-417014/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: us.gcr.io/ticketing-dev-417014/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    